tarantool/tntcxx

doc/tntcxx_api.rst, doc/tntcxx_getting_started.rst
There were some warnings while building the docs because the paths for _includes were different in source file and in tarantool/doc.
=> fix documentation build warnings

.github/workflows/destroy-deployment.yml, .github/workflows/pull-translation.yml, .github/workflows/push-translation.yml, .github/workflows/upload-translations.yml, .gitignore, doc/README.md, doc/cleanup.py, doc/conf.py, doc/crowdin.yaml, doc/locale/ru/LC_MESSAGES/doc/tntcxx_api.po, doc/locale/ru/LC_MESSAGES/doc/tntcxx_getting_started.po, doc/requirements.txt
Documentation sources are .rst files where a tech writer or a developer writes documentation. As soon as we have two languages supported on our website we need to maintain translated 100% of the documentation. For translation, we use Crowdin - saas solution for translating any texts.  
While a new PR with changes in .rst is opened, the translations for these changes are preparing by translators in Crowdin.  
When the translations are ready we can run __Pull translations__ job to download and commit translations into the PR branch.  
This diagram shows how the process works:
- add cleanup.py for re-arranging .po files and initial re-arranged .po files
- push-translation.yml push translation sources to Crowdin on pull request when .rst is changed, create a deployment with a link to Crowdin …
=> Add documentation translation workflows and configs

src/Utils/Mempool.hpp, src/mpp/Constants.hpp
This patchset adds a missing include in mpp and replaces `.` by `->` in Mempool.
=> Minor compilation fixes.

.github/workflows/debug.yml
The runner uses Tarantool 2.11 for tests for stability and have both release and debug versions.
=> ci: build and test tntcxx on ubuntu 

.github/workflows/ubuntu.yml, src/Utils/Common.hpp, test/BufferPerfTest.cpp, test/Utils/TupleReader.hpp
The patch provides CI with ubuntu 22.04 runner and fixes all build issues related to both ubuntu 22.04 and 20.04.
=> ci: build and test tntcxx on ubuntu 22.04

.github/workflows/testing.yml, src/Utils/Traits.hpp, test/EncDecTest.cpp, test/Utils/System.hpp
The project is tested in both Release and Debug modes on each version of
macos. Tarantool is installed from brew, the last stable version is used.
=> ci: build and test tntcxx on macos 11 and 12

src/Utils/Common.hpp, src/Utils/Traits.hpp, src/mpp/ClassRule.hpp, src/mpp/Dec.hpp, src/mpp/Enc.hpp, test/CommonUnitTest.cpp, test/EncDecTest.cpp, test/TraitsUnitTest.cpp
Now it became possible to pass an object of any class to
mpp::encode and mpp::decode if a co/dec rule is supplied.
There are two ways to specify a rule for a particular class:
* through static member of the class, that is `mpp` member for
ecoding/decoding, `mpp_enc` for encoding only and `mpp_dec` fo
decoding only.
* via partial specialization of special global class, that is
`mpp_rule` for ecoding/decoding, `mpp_enc_rule` for ecoding and
`mpp_dec_rule` for decoding. In any of these cases a static
member `value` is expected in the specialization.
In any case the value of the encoding rule must be a constexpr
expression that could contain any values, including standard
aggregates like std::tuple and pointers to members of the class
that must be encoded/decoded.
Note that one can specify …
=>  mpp: introduce object encoding/decoding

src/mpp/Constants.hpp, src/mpp/Dec.hpp, src/mpp/Enc.hpp, test/EncDecTest.cpp
The patch populates mpp::encode and mpp::decode functions with optional objects support. An empty optional is encoded as MP_NIL, and MP_NIL is decoded as an empty optional. Otherwise, underlying objects are encoded/decoded just like without optional.
=> Support optional in encoder and decoder

CMakeLists.txt, README.md
Currently, using our library in one's CMake project is a mess. It requires manually linking against our dependencies and manually adding include directories.
To fix this, let's add a `tntcxx::tntcxx` interface target, linking against would be enough to use our library in one's CMake project.
Closes #44
=> Build: create `tntcxx::tntcxx` interface library target

src/Utils/Traits.hpp, src/mpp/Dec.hpp, test/EncDecTest.cpp, test/TraitsUnitTest.cpp
The patch adds support of `mpp::as_raw` to new decoder. Wrapped value must be a pair of iterators (it can be wrapped to optional). When it is used, corresponding value is skipped but an iterator pointing to the value in buffer is saved. Also, one can pass `pair<it_t, it_t>` without `as_raw` tag.
NB: Encoder is not provided with `pair<it_t, it_t>` support in this patch - it will be later.
=> Dec: allow to save iterator to value instead of decoding

.github/workflows/testing.yml, examples/Simple.cpp
Accidentally, release workflows are built with ReleaseWithDebInfo. This build type is not valid - that's why NDEBUG is not set, and all workflows are built in Debug mode actually. Let's fix this mistake and all associated compilation errors along the way.
=> CI: build release workflows with RelWithDebInfo type

CMakeLists.txt, examples/CMakeLists.txt, examples/Sql.cpp, src/Client/Connection.hpp, src/Client/IprotoConstants.hpp, src/Client/RequestEncoder.hpp, src/Client/ResponseReader.hpp, test/ClientTest.cpp, test/cfg.lua
The patch provides client with execute and prepare requests. Execute allows to pass an SQL statement or id of a prepared statement and parameters for it. Response body is populated with sql fields.
Closes #34
=> Client: support execute and prepare 

.github/workflows/reusable-testing.yml
Valgrind runners fail to fetch valgrind from apt, so let's do apt upgrade before apt install - it solves the problem.
=> ci: fix valgrind workflow

.clang-format, .editorconfig, .githooks/pre-commit, .github/workflows/linting.yml
This patch sets up code formatting infrastructure. Supersedes #17.
=> Build, CI: set up code formatting infrastructure

.clang-format, src/mpp/Dec.hpp, src/mpp/Rules.hpp
This patch optimizes the decoding of optional and variant values for scalar types.
Closes #84
=> Decoder: optimize decoding of optional and variant for scalar types

README.md, doc/tntcxx_api.rst
The commit completely rewrites decoding section since the decoder was reworked. Along the way, commit marks all snippets as `c++` code and fixes some mild inconveniences.
Closes #94
=> readme: update README.md

.github/workflows/reusable-testing.yml, .github/workflows/testing.yml, src/Buffer/Buffer.hpp
The patchset fixes `tntcxx` CI.
=> ci: fix ci

.github/actions/build-tntcxx/action.yml, .github/workflows/testing.yml, src/Buffer/Buffer.hpp, src/Client/ResponseReader.hpp, test/BufferUnitTest.cpp, test/ClientTest.cpp
See commits for details.
The PR fixes CI along the way.
Closes #106
=> client: use universal reference in data decoder

.clang-format, .github/actions/build-tntcxx/action.yml, .github/actions/setup-tarantool/action.yml, .github/workflows/reusable-testing.yml, .github/workflows/testing.yml, CMakeLists.txt, README.md, src/Buffer/Buffer.hpp, src/Client/Connection.hpp, src/Client/LibevNetProvider.hpp, src/Client/RequestEncoder.hpp, src/Utils/Logger.hpp, src/Utils/Mempool.hpp, test/ClientMultithreadTest.cpp, test/MempoolUnitTest.cpp
The commit adapts connector to multithreaded scenarios and populates CI with thread sanitizer. See commits for details.
Closes #110
=> client: support multi-threading

src/Client/Connection.hpp, src/Client/Connector.hpp, test/ClientTest.cpp
The argument was completely broken - the commit fixes it.
Along the way, fixed a crash when a decoded future appeared in `m_ReadyToDecode`. See the commits for details.
Closes #112
Closes https://github.com/tarantool/tntcxx/issues/124
=> client: fix `result` argument of `wait`

src/Client/Connector.hpp, test/ClientTest.cpp
This patchset fixes some bugs with the Connector `wait*` methods.
Closes #121
closes #133
=> Wait methods fixes
